#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""The MIB manager screen — a list that reaches the bottom, and one row per module.

Two separate things went wrong in the same modal, and both are the kind that no Python test
would ever see.

**The list stopped short of the bottom.** Its height was pinned in the markup
(``max-height:35vh``) and the modal BODY was what scrolled. That is fine at exactly one
dialog size and wrong at every other: this modal can be dragged to a new size and maximized
to 95vh, and at 95vh the list used a third of the height while the rest of the modal sat
empty. The fix is the chain the rest of the panel already uses — ``.ss-vfill`` down to a
single ``.ss-vscroll`` — so the height is whatever the dialog turns out to have. It only
holds if EVERY link is present, which is what this file checks: a chain with one link
missing collapses back to content height and looks exactly like the bug.

**And the list was keyed by file, not by module.** The API answers ``raw`` (.mib) and
``compiled`` (.py); shown as two columns those are the same MIB twice, so "is this one
compiled?" meant reading both columns and comparing by eye. The list is now keyed the way
pysmi is keyed — by module name — and the file pair is a state on the row.
"""

import os
import re

from tests.helpers import _fn, _read, _strip_comments

SRC = os.path.abspath(__file__).split(os.sep + 'tests' + os.sep)[0]
WEB = os.path.join(SRC, 'watchfuls', 'snmp', 'web')
UI = os.path.join(WEB, '_ui.html')
MODALS = os.path.join(WEB, '_modals.html')
STYLES = os.path.join(WEB, '_styles.html')
CSS = os.path.join(SRC, 'lib', 'web_admin', 'static', 'css', 'web_admin.css')
# The sources these guards read, named once. They have moved trees before — the resolver is
# core now and the admin is still the watchful's — and a path spelled inline at ten call
# sites is ten chances to leave one behind, reading a file that is not there.
RESOLVER = os.path.join(SRC, 'lib', 'core', 'snmp', 'mibs', 'resolver.py')
MIB_ADMIN = os.path.join(SRC, 'watchfuls', 'snmp', 'mib_admin.py')
SNMP_INIT = os.path.join(SRC, 'watchfuls', 'snmp', '__init__.py')
LINT = os.path.join(SRC, 'lib', 'core', 'snmp', 'mibs', 'lint.py')

TPL_ID = 'snmpMibsPageTpl'


def _pyfn(src: str, name: str) -> str:
    """The body of a top-level PYTHON function — `_fn` is a JavaScript extractor.

    Sliced to the next top-level `def` or to the END of the file: the function this guard
    reads most is the last one in its module, and `index()` on a needle that is not there
    raises rather than answering.
    """
    i = src.index('def %s' % name)
    j = src.find('\ndef ', i + 1)
    return src[i:] if j < 0 else src[i:j]


IMPORT_TPL_ID = 'snmpImportPageTpl'


def _import_markup() -> str:
    """The import VIEW's markup. Same file and same kind of thing as the library's: a
    `<template>` the section clones into the pane the core gave it."""
    src = _read(MODALS)
    i = src.index('id="%s"' % IMPORT_TPL_ID)
    return src[i:src.index('</template>', i)]


COMPILE_TPL_ID = 'snmpCompilePageTpl'


def _compile_markup() -> str:
    """The compile VIEW's markup. It was a button, a fold and a bar stacked over the list;
    it is a place of its own now, and the same kind of inert `<template>` as the others."""
    src = _read(MODALS)
    i = src.index('id="%s"' % COMPILE_TPL_ID)
    return src[i:src.index('</template>', i)]


def _manager_markup() -> str:
    """The manager's markup only — the file also holds the browser and details modals.

    A ``<template>`` now and not a modal: the manager is a SECTION of the System panel, its
    pane is generated by the core, and the module ships the markup inert for the render to
    clone. Reading it here is what it always was — markup is markup, wherever it waits.
    """
    src = _read(MODALS)
    i = src.index('id="%s"' % TPL_ID)
    return src[i:src.index('</template>', i)]


class TestTheListReachesTheBottom:
    """Every link of the fill chain, because a chain is only as good as its weakest link and
    a broken one fails silently: the list simply stops where its content stops."""

    def test_the_pane_is_given_a_height_to_hand_down(self):
        """`.ss-vfill` distributes a height; it does not invent one. In a modal that height
        came from `modal-dialog-scrollable`; in a section it comes from the shell — the
        active pane is a flex column that fills the viewport below the header — and the
        container the core generates for a module page opts into the chain."""
        css = _read(CSS)
        m = re.search(r'\.container-fluid > \.tab-content > \.tab-pane\.active\s*\{([^}]*)\}', css)
        assert m, 'the active pane no longer fills — nothing below it can either'
        assert 'flex-direction: column' in m.group(1) and 'min-height: 0' in m.group(1)
        dash = _read(os.path.join(SRC, 'lib', 'web_admin', 'templates', 'dashboard.html'))
        assert 'id="{{ p.id }}-container" class="ss-vfill"' in dash

    def test_the_markup_fills_it(self):
        """The template's own root: the pane hands a height down and something has to take
        it. Without this the manager is content-sized inside a full-height pane, which is the
        old bug with a different frame around it."""
        markup = _manager_markup()
        root = re.search(r'<div class="([^"]*ss-vfill[^"]*)"', markup)
        assert root, 'the manager markup takes no height from its pane'


    def test_the_rule_for_a_modal_that_fills_is_still_there(self):
        """The manager left, the rule stays: `modal-dialog-scrollable` puts `overflow-y: auto`
        on the body, which is the opposite of what a fill chain needs, and the details modal
        the manager opens still relies on it."""
        css = _read(CSS)
        m = re.search(r'\.modal-body\.ss-vfill\s*\{([^}]*)\}', css)
        assert m, '.modal-body.ss-vfill is gone — a filling modal body will scroll again'
        assert 'overflow' in m.group(1) and 'hidden' in m.group(1)

    def test_the_list_container_is_the_link_that_grows_and_scrolls(self):
        assert 'id="mibManagerBody" class="ss-vfill"' in _manager_markup()
        assert "'<div id=\"mibList\" class=\"ss-vscroll" in _read(UI)

    def test_nothing_in_the_manager_pins_a_height_of_its_own(self):
        """The bug, in its original form: `max-height:35vh` on the lists. A height pinned
        anywhere in the chain wins over the height being handed down, and the modal goes back
        to having dead space under a list that stopped early."""
        parts = [_manager_markup()]
        # Only the manager's own renderers: the same file also builds the browser tree and
        # the details tables, which are capped modals of their own.
        ui = _strip_comments(_read(UI))
        parts += [_fn(ui, name) for name in
                  ('_mibRender', '_mibListBarHtml', '_mibRailHtml', '_mibRow')]
        for src in parts:
            hits = re.findall(r'(?:max-)?height\s*:\s*\d+vh', src)
            assert not hits, f'a viewport height is pinned in the manager: {hits}'

    def test_the_fill_chain_is_never_sized_by_id(self):
        """Layout behaviour lives in reusable classes; per-id CSS is how the same rule
        ends up written three times and fixed once.

        Only the ids of the CHAIN. A single widget may still be sized by id — an input
        that must not grow inside a flex row is one rule about one input — and forbidding
        that would be forbidding CSS.
        """
        styles = _strip_comments(_read(STYLES))
        for _id in ('mibManagerBody', 'snmp-container', 'tab-snmp'):
            for prop in ('min-height', 'flex:', 'overflow-y', 'height'):
                assert not re.search(r'#%s[^{]*\{[^}]*%s' % (_id, re.escape(prop)),
                                     styles), \
                    f'#{_id} sets {prop} by id — the chain is a class, not an id'

    def test_everything_above_the_list_refuses_to_shrink(self):
        """A flex item shrinks before its siblings scroll. If the toolbar can shrink, a long
        list squashes the buttons instead of scrolling — so the fixed parts say so."""
        markup = _manager_markup()
        body = markup[markup.index('ss-vfill'):]
        # The direct children of the body that are not the part that grows.
        fixed = re.findall(r'\n            <(?:div|details)[^>]*class="([^"]*)"', body)
        assert fixed, 'the body has no direct children — this guard needs rewriting'
        for cls in fixed:
            # The two things allowed to grow: a column that fills, and the ROW of columns
            # the rail and the list sit in.
            if 'ss-vfill' in cls or 'ss-hfill' in cls:
                continue
            assert 'flex-shrink-0' in cls, f'a fixed row can shrink instead: {cls}'

    def test_the_rail_is_the_panel_s_rail_and_not_a_second_one(self):
        """`ssRailShell` is what Configuration and Backups are built on: a `<nav>` down the
        left of the pane, flush to the top, with the section's head and body beside it. A
        module drawing its own would be two rails that should look identical and will not."""
        ui = _read(UI)
        assert 'ssRailShell(' in _fn(ui, '_snmpRailShell')
        assert 'ss-rail-item' in _fn(ui, '_mibRailItem')
        assert 'ss-rail-head' in _fn(ui, '_mibRailHtml')
        styles = _strip_comments(_read(STYLES))
        assert '.mib-rail' not in styles, 'the module keeps a copy of the shared rail'

    def test_a_pane_that_already_bleeds_does_not_bleed_twice(self):
        """The shell cancels the container's gutters and its top padding with negative
        margins. A module's pane is `.ss-fullbleed` and has cancelled the same ones, so a
        shell inside one hangs a gutter past both edges of the window."""
        css = _read(CSS)
        assert re.search(r'\.ss-fullbleed\s*>\s*\.ss-shell\s*\{[^}]*margin:\s*0', css)

    def test_the_rail_goes_up_with_the_view_that_has_a_list(self):
        """A rail filters a list, and importing and compiling have no list — and it
        restructures the pane around the container the templates are cloned into, so it moves
        once per view change and never under a list being drawn."""
        ui = _read(UI)
        assert "_snmpRailShell(view)" in _fn(ui, 'renderSnmpMibsPage')
        body = _fn(ui, '_snmpRailShell')
        # Which views have one is decided in ONE place, by naming the body each fills.
        assert "'mibRailBody'" in body and "'snmpProfRailBody'" in body
        assert ": ''" in body, 'every view gets a rail, including the ones with no list'

    def test_the_two_railed_views_share_one_shell(self):
        """The shell restructures the pane; two of them would be two rails in one pane, drawn
        at different heights by whichever ran last. What differs is the CONTENT, so the body
        is replaced when the view changes — and left alone when it does not, because a rail
        rebuilt on every render loses the scroll position of a four-hundred-folder tree."""
        body = _fn(_read(UI), '_snmpRailShell')
        assert 'dataset.snmpRail !== view' in body, 'the rail is rebuilt on every render'
        assert 'dataset.snmpRail = view' in body

    def test_the_search_box_is_built_once(self):
        """It lives in the rail, and the rail is repainted on every keystroke: rebuilt with
        it, the cursor leaves the box being typed in. The BODY is what gets repainted."""
        ui = _read(UI)
        assert "getElementById('mibRailBody')" in _fn(ui, '_mibFilterLists')
        assert "'mibRailBody'" in _fn(ui, '_snmpRailShell')


class TestTheMarkupCloses:
    """A stray `</div>` is invisible in a diff and unmistakable on screen. This one closed
    the padded column immediately after opening it: everything below landed outside it, the
    now-empty column kept its `.ss-vfill` and grew to fill the pane, and the section became a
    header, a hole the height of the viewport, and a list with no margins. All three views at
    once, from one edit that removed a block and left its closing tag behind.

    Counting tags is not parsing HTML — but the failure mode here is exactly a count, and the
    browser will not complain: it re-nests silently and paints something almost right.
    """

    def test_every_view_balances_its_divs(self):
        for name, markup in (('library', _manager_markup()),
                             ('import', _import_markup()),
                             ('compile', _compile_markup())):
            opens = len(re.findall(r'<div\b', markup))
            closes = len(re.findall(r'</div>', markup))
            assert opens == closes, (
                f'{name}: {opens} <div> and {closes} </div> — a view whose columns do not '
                'close where they should paints a hole and loses its margins')

    def test_the_padded_column_holds_the_view(self):
        """The head and the progress strip are outside it on purpose — they belong to the
        frame — and everything the view is ABOUT is inside it. An empty one is the shape the
        bug took."""
        for markup in (_manager_markup(), _import_markup(), _compile_markup()):
            i = markup.index('class="ss-vfill p-3"')
            rest = markup[i:]
            assert rest.count('<div') > 3, 'the padded column is empty'
            assert 'ss-toolbar' not in rest, 'the head is inside the padding'
            assert 'mibProgressSection' not in rest, 'the progress strip is inside the padding'


class TestOneRowPerModule:

    def test_the_list_is_keyed_by_module_name(self):
        """Not by file: `raw` and `compiled` are the same MIB twice, and two vendors can each
        ship a copy of the same standard module — which is one thing to compile, not two."""
        body = _fn(_read(UI), '_mibRows')
        assert 'raws.push' in body, 'a module has to hold every source that claims it'
        assert "state = " in body and "'dep'" in body and "'pending'" in body

    def test_a_module_with_no_source_is_a_dependency_or_a_leftover(self):
        """A .py with no .mib beside it is one of two things, and they are opposites. If
        pysmi read it out of `raw/`, that source has been deleted since and the .py is a
        leftover nobody can rebuild. If it did not, pysmi resolved it elsewhere — its own
        bundled MIBs, or over HTTP — and it is a dependency the modules importing it need.
        Calling both "dep" hid three hundred and seventy-four of the first kind among three
        of the second."""
        ui = _read(UI)
        assert "!r.raws.length ? (r.pySource ? 'stray' : 'dep')" in _strip_comments(ui)
        # …and neither can be compiled: the compile action is conditional on a source.
        assert 'r.raws.length && r.py' not in _fn(ui, '_compileSelected')
        assert 'r.raws.length' in _fn(ui, '_compileSelected')

    def test_deleting_a_row_deletes_every_file_it_stands_for(self):
        """The row is a module; the files behind it are an implementation detail. Deleting
        one and silently leaving the other is how a 'deleted' MIB keeps resolving."""
        body = _fn(_read(UI), '_mibArtifacts')
        assert "kind: 'raw'" in body and "kind: 'compiled'" in body

    def test_the_selection_survives_a_module_being_compiled(self):
        """The list re-renders on every poll while a compile runs. Keyed by file, a row's
        identity changes the moment its .py appears and the tick under the user's cursor
        would move; keyed by module, it does not."""
        assert 'let _mibSelection = new Set();' in _read(UI)
        assert '_mibFilterLists();' in _fn(_read(UI), '_mibRefreshCompiled')

    def test_the_states_carry_the_counts(self):
        """"What is still pending" is the question this screen exists to answer, so it is on
        screen before anything is typed or clicked."""
        body = _fn(_read(UI), '_mibStateDefs')
        for state in ('pending', 'compiled', 'dep'):
            assert "'%s'" % state in body


class TestAFailureIsItsOwnState:
    """A vendor MIB that cannot be parsed stays pending for ever, and "pending" is also what a
    MIB nobody has compiled yet says — so on its own it reads as "the button is broken". They
    need opposite things done to them: one a click, the other a file that is not broken. pysmi
    knows the reason (`Bad grammar near offset 558 … line 21`) and the panel used to drop it.

    SYNOLOGY-SMB-MIB is the file that made this obvious: Synology ships it malformed, every
    descriptor starting uppercase where SMI wants a value reference, so the parser stops at
    the first table definition. Nothing here can fix that file — it can only say so.
    """

    def test_the_reason_is_a_state_and_not_a_flavour_of_pending(self):
        body = _fn(_read(UI), '_mibRows')
        assert "'failed'" in body, 'a recorded failure has to be its own state'

    def test_it_has_a_line_of_its_own(self):
        """After a run of two hundred, "what failed" has to be one click, not a scroll."""
        assert "'failed'" in _fn(_read(UI), '_mibStateDefs')
        assert 'failed: 0' in _fn(_read(UI), '_mibCounts')

    def test_the_reason_outlives_the_page(self):
        """Held in the page it died with the modal, which is the one place it was needed: a
        compile of two hundred is not watched to the end, and the failures are what you come
        back for. The list answers with them."""
        ui = _strip_comments(_read(UI))
        assert '_mibCompileErrors' not in ui, 'the page must not keep its own copy'
        assert '_mibData.errors' in _fn(ui, '_mibRows')

    def test_the_whole_message_is_one_click_away(self):
        """A parser message is a sentence with an offset in it: too long for a row, too
        important to truncate."""
        body = _fn(_read(UI), '_mibStateBadge')
        assert '_mibShowError' in body and 'bg-danger' in body
        assert body.index('if (r.error)') < body.index("state === 'compiled'"), \
            'the reason has to be checked before the plain states'

    def test_nothing_reworded_it_on_the_way(self):
        """`showInfoModal` escapes its values, which is why the reason is handed to it as a
        value and not as markup — and why it arrives verbatim."""
        body = _fn(_read(UI), '_mibShowError')
        assert 'r.error' in body and 'showInfoModal' in body

    def test_the_reason_reaches_the_browser_at_all(self):
        """Four hops, and it is dropped at any one of them: pysmi's status carries it, the
        resolver classifies, the job records, the list answers."""
        res = _read(RESOLVER)
        adm = _read(MIB_ADMIN)
        assert "'errors':  _compile_errors(failed, _status)" in res, \
            'the reason is looked up under the same name the failure was filed under'
        assert "'errors':    result.get('errors', {})" in adm
        assert "'errors':          errors," in adm


class TestTheCompilerIsNotTheOnlyThingThatReadsTheFile:
    """pysmi says where it gave up ("Bad grammar near offset 558") and names the symbols it
    could not place ("Unknown parents for symbols: netSnmpPassCounter64") — both one step away
    from the thing to change. The linter says the thing itself, with the line."""

    def test_the_editor_can_ask_before_saving(self):
        """On what is on screen, not on what is on disk: the point is to answer while the
        change is still a change."""
        body = _fn(_read(UI), '_mibLintNow')
        assert '_mibSrcEditor.getValue()' in body

    def test_a_clean_file_is_told_so_out_loud(self):
        """Pressing a check button and getting nothing back is indistinguishable from a check
        button that does not work."""
        assert 'mib_lint_clean' in _fn(_read(UI), '_mibLintNow')

    def test_the_failure_modal_carries_the_hints(self):
        assert '_mibLint(' in _fn(_read(UI), '_mibShowError')

    def test_the_hints_are_read_now_and_not_stored_with_the_error(self):
        """An error kept from last week beside hints from last week is two stale things
        agreeing with each other. The file is what it is right now."""
        adm = _read(MIB_ADMIN)
        assert '\'hints\'' not in adm, 'findings are being frozen into the failure store'
        assert 'lint_mib' in adm, 'nothing reads them at all'

    def test_a_version_can_be_removed_by_hand(self):
        """The history is not tidied automatically beyond the cap — but a version somebody
        knows is junk should not have to stay for ever."""
        ui = _read(UI)
        assert '_mibVersionDelete' in _fn(ui, '_mibVersionRow')
        assert 'showConfirmModal' in _fn(ui, '_mibVersionDelete')

    def test_deleting_the_vendors_own_says_what_it_is(self):
        """v1 is the only version that cannot be got back from anywhere: the file it came
        from has been overwritten by every save since."""
        assert 'mib_version_delete_original_confirm' in _fn(_read(UI), '_mibVersionDelete')

    def test_it_reads_and_does_not_write(self):
        """Checking a file must never be a thing that changes it — and it audits a row per
        look unless it is declared read-only."""
        init = _read(SNMP_INIT)
        acts = init[init.index('WATCHFUL_ACTIONS'):init.index('WATCHFUL_TOOLBAR')]
        ro = acts[acts.index('READ_ONLY_ACTIONS'):]
        assert "'lint_mib_source'" in acts and "'lint_mib_source'" in ro


class TestTheSourceIsReadableAgainstTheError:
    """The reason names a LINE, and the viewer used to be a `<pre>` — no numbers to count, so
    you scrolled and guessed. CodeMirror was already in the panel for the notification
    template editor; it brings the numbering, and one mode brings the colour."""

    def test_the_loader_is_shared_and_not_borrowed_from_a_config_tab(self):
        """A watchful reaching into `partials/cfg/notify/` for a function is a dependency
        nobody would look for, and the first tidy-up of that tab breaks the MIB viewer."""
        core = os.path.join(SRC, 'lib', 'web_admin', 'templates', 'partials', 'core',
                            '_codemirror.html')
        assert os.path.isfile(core), 'the CodeMirror loader is not core'
        assert 'function _ensureCodeMirror' in _read(core)
        tpl = _read(os.path.join(SRC, 'lib', 'web_admin', 'templates', 'partials', 'cfg',
                                 'notify', '_tpl_html.html'))
        assert 'function _ensureCodeMirror' not in tpl, 'two loaders is one too many'
        sections = _read(os.path.join(SRC, 'lib', 'web_admin', 'templates', 'partials',
                                      '_js_sections.html'))
        assert 'partials/core/_codemirror.html' in sections

    def test_there_is_a_mode_for_mibs_because_codemirror_ships_none(self):
        """The bundled modes are css, xml, javascript and htmlmixed. ASN.1/SMI is not among
        them, so the colour is this module's to define."""
        body = _fn(_read(UI), '_mibDefineMode')
        assert "defineMode('mib'" in body

    def test_the_mode_lexes_and_does_not_parse(self):
        """It has to colour a file that DOES NOT parse — which is exactly when somebody is
        reading it. Anything that needed the grammar to hold would give up on the one file
        worth looking at."""
        ui = _read(UI)
        body = _fn(ui, '_mibDefineMode')
        assert 'startState' in body and 'token:' in body
        # The distinction a malformed vendor MIB gets wrong: in SMI the CASE of the first
        # letter IS the meaning — uppercase a type reference, lowercase a value.
        assert '/^[A-Z]/.test(t)' in body

    def test_a_string_survives_the_end_of_a_line(self):
        """A DESCRIPTION runs over many lines. A mode that closed the string at the newline
        would colour the rest of the file as code, from the first description onwards."""
        assert 'state.inString' in _fn(_read(UI), '_mibDefineMode')

    def test_a_viewer_that_cannot_be_pretty_is_still_a_viewer(self):
        """The loader can fail — a missing asset, a locked-down browser. Falling back to the
        old <pre> costs nothing; failing to show the source costs the whole screen."""
        body = _fn(_read(UI), '_mibRenderSource')
        assert '_ensureCodeMirror' in body
        assert '<pre' in body, 'no fallback: a failed load would blank the source'

    def test_arriving_from_a_failure_opens_on_the_failing_line(self):
        """The value of the reason IS the line; scrolling to it by hand loses it."""
        ui = _read(UI)
        assert 'line\\s+(\\d+)' in _fn(ui, '_mibErrorLine') or \
               'line\\s' in _fn(ui, '_mibErrorLine')
        assert '_mibErrorLine(r.error)' in _fn(ui, '_mibRow')
        assert 'mib-src-badline' in _fn(ui, '_mibRenderSource')


class TestTheDetailModalIsTwoTabs:
    """One modal was a stack of three collapsibles — a header, imports, an objects table and
    the source at the bottom, each opening and closing over the others. Split in two, each
    half gets the whole height: what the file DECLARES, and what it SAYS. Both viewers do it,
    because both have a source: the raw one an ASN.1 MIB, the compiled one the Python module
    pysmi wrote."""

    def test_both_viewers_offer_the_same_pair(self):
        ui = _read(UI)
        for name in ('_mibShowRawDetails', '_mibShowDetails'):
            body = _fn(ui, name)
            assert 'nav-tabs' in body, f'{name} still stacks its sections'
            assert 'mibTabDecl' in body and 'mibTabCode' in body

    def test_the_pane_is_the_scroller_and_not_a_box_inside_it(self):
        """A box of a fixed height inside a pane that already has one is a keyhole with a
        scrollbar on each side."""
        ui = _read(UI)
        for name in ('_mibShowRawDetails', '_mibShowDetails'):
            body = _fn(ui, name)
            assert 'max-height:45vh' not in body, f'{name} still pins a height inside a pane'
            assert 'ss-vscroll' in body

    def test_a_pane_is_allowed_to_be_a_flex_column(self):
        """Bootstrap's `.tab-content > .active { display: block }` outranks a class-only
        `display: flex`: the class sits in the markup, the layout ignores it, and nothing
        says so. The chain needs the specificity won back."""
        css = _read(CSS)
        assert re.search(r'\.tab-content > \.tab-pane\.active\.ss-vfill\s*\{', css)

    def test_the_editor_is_told_to_measure_again_when_its_tab_opens(self):
        """CodeMirror measures itself when it is built, and a hidden tab has no size to
        measure: built behind the other tab it comes out a few pixels tall and stays that way
        until something makes it look again."""
        ui = _read(UI)
        for name in ('_mibShowRawDetails', '_mibShowDetails'):
            assert "'shown.bs.tab'" in _fn(ui, name), f'{name} never refreshes the editor'

    def test_what_pysmi_writes_gets_its_own_mode(self):
        """The compiled half is Python, and CodeMirror 5 ships no mode for it here either —
        the bundled ones are css, xml, javascript and htmlmixed."""
        body = _fn(_read(UI), '_mibDefinePyMode')
        assert "defineMode('pysnmp'" in body
        assert 'state.triple' in body, 'a docstring outlives its line'
        assert "'pysnmp'" in _fn(_read(UI), '_mibShowDetails')


class TestAMibCanBeFixedAndTakenBack:
    """Vendors ship broken MIBs, and there is nothing to do about that from here except let
    somebody correct one. A correction nobody can undo is one nobody dares make, so the
    history is the feature and the pencil is only the button."""

    def test_the_editor_starts_read_only(self):
        """This modal is opened to READ far more often than to change anything, and a text
        box you can type into by accident is a file you can break by accident."""
        ui = _read(UI)
        assert 'readOnly:    true' in _fn(ui, '_mibRenderSource')
        assert "setOption('readOnly', !_mibEditOn)" in _fn(ui, '_mibEditToggle')

    def test_saving_says_the_mib_has_to_be_compiled_again(self):
        """The compiled module is now older than its source; leaving that unsaid is how an
        edit gets made, believed, and never actually used by anything."""
        assert 'mib_edit_saved' in _fn(_read(UI), '_mibEditSave')

    def test_the_list_is_reloaded_after_an_edit(self):
        """The file changed, so what the list says about it did: its compiled module is now
        stale and any recorded failure was about bytes that are gone."""
        assert '_mibLoad()' in _fn(_read(UI), '_mibEditSave')

    def test_restoring_asks_first(self):
        """It overwrites the file every check resolves through."""
        assert 'showConfirmModal' in _fn(_read(UI), '_mibVersionRestore')

    def test_viewing_an_old_version_cannot_be_mistaken_for_the_file(self):
        """An old version shown in the same editor as the current one, unlabelled, is how
        the wrong content gets edited on top of and saved."""
        body = _fn(_read(UI), '_mibVersionView')
        assert 'mib_version_viewing' in body
        assert '_mibEditToggle(false)' in body


class TestLeavingTheEditorCostsNothing:
    """Cancelling an edit used to re-fetch the file and rebuild the modal around it — which
    threw away the tab you were on, the scroll position and the editor itself, to undo
    something already sitting in memory. On screen that is the whole modal flashing to put
    back what you were already looking at."""

    def test_cancelling_puts_back_a_value_it_already_holds(self):
        body = _fn(_read(UI), '_mibEditCancel')
        assert 'setValue(_mibSrcOnDisk)' in body
        assert 'apiPost' not in body and '_mibShowRawDetails' not in body, \
            'leaving the editor fetches and rebuilds again'

    def test_the_editor_keeps_what_it_was_handed(self):
        """There is nothing to put back otherwise, and the file would have to be fetched to
        find out what it already said."""
        assert '_mibSrcOnDisk = text' in _fn(_read(UI), '_mibRenderSource')

    def test_saving_redraws_the_one_pane_that_went_stale(self):
        """What the file declares changed, so that tab is quietly wrong — and it is one pane,
        not a modal."""
        body = _fn(_read(UI), '_mibEditSave')
        assert '_mibDeclRefresh()' in body
        assert '_mibShowRawDetails' not in body, 'saving rebuilds the modal'

    def test_restoring_does_not_rebuild_it_either(self):
        body = _fn(_read(UI), '_mibVersionRestoreConfirmed')
        assert '_mibDeclRefresh()' in body
        assert '_mibShowRawDetails' not in body
        assert 'setValue' in body, 'it reloads the modal to see what it just wrote'

    def test_the_declarations_pane_is_never_empty(self):
        """A pane with nothing in it reads as a screen that failed to load — and a MIB whose
        syntax breaks mid-file really does declare nothing this parser can see, which is worth
        saying, since the source tab next door is where the answer is."""
        body = _fn(_read(UI), '_mibDeclHtml')
        assert 'mib_details_none' in body
        assert body.rindex('mib_details_none') > body.index('objects_detail')

    def test_an_open_version_list_is_redrawn_after_a_save(self):
        """A save adds a version; a list left open showing the state before it lies about the
        thing that just happened."""
        assert '_mibVersionsDraw()' in _fn(_read(UI), '_mibEditSave')


class TestNothingIsKeptWhereItCannotBeReached:
    """Deleting a MIB keeps its versions, which is right — and drawing nothing for them was
    not: a thing that exists, cannot be seen, cannot be brought back and cannot be cleared out
    is worse than either keeping or dropping it."""

    def test_a_history_with_no_file_is_a_row(self):
        assert "'orphan'" in _fn(_read(UI), '_mibRows')
        assert 'orphan' in _fn(_read(UI), '_mibCounts')

    def test_it_has_a_chip_so_it_can_be_found(self):
        assert "'orphan'" in _fn(_read(UI), '_mibStateDefs')

    def test_the_row_offers_the_two_things_that_apply_to_it(self):
        """There is no file: compiling, viewing the source and deleting the file are all
        about something that is not there."""
        body = _fn(_read(UI), '_mibRow')
        assert '_mibOrphanRestore' in body and '_mibOrphanForget' in body

    def test_deleting_a_mib_offers_to_take_the_history(self):
        """Offered at the moment of deciding — asking afterwards in its own dialog is asking
        once the moment has passed — and never ticked by default."""
        body = _fn(_read(UI), '_mibDeleteRow')
        assert 'mib_delete_with_history' in body
        assert 'checked: false' in body

    def test_the_confirm_modal_grew_that_checkbox_generically(self):
        """One opt-in checkbox on the shared confirm dialog, the same shape the reason field
        already had — not a dialog of this module's own."""
        toast = _read(os.path.join(SRC, 'lib', 'web_admin', 'templates', 'partials', 'core',
                                   '_toast.html'))
        assert '_confirmModalCheckOpts' in toast
        dialogs = _read(os.path.join(SRC, 'lib', 'web_admin', 'templates', 'partials',
                                     'modals', '_dialogs.html'))
        assert 'confirmModalCheckWrap' in dialogs


class TestARowIsAModuleAndNotAFileName:
    """`trunk.mib` declares IEEE8023-LAG-MIB. pysmi locates a source by the FILE name and
    writes the MODULE name, so a screen keyed on the file asks about a `.py` that will never
    be written: the MIB compiles, the compiler says "already up to date", and the row says
    pending for ever. On a real library that was 132 pending of which 117 were an illusion."""

    def test_the_row_is_keyed_by_what_the_file_declares(self):
        body = _fn(_read(UI), '_mibRows')
        assert 'f.module' in body, 'keyed on the file name, half a vendor archive never lands'

    def test_the_file_name_is_still_shown_when_it_differs(self):
        """A row reading IEEE8023-LAG-MIB while the folder holds `trunk.mib` is a row nobody
        can match to a file, and matching them is most of what this screen is for."""
        rows = _fn(_read(UI), '_mibRows')
        assert 'r.file =' in rows
        assert 'r.file' in _fn(_read(UI), '_mibRow')

    def test_a_compiled_module_is_a_dependency_only_if_nothing_declares_it(self):
        """Compared against file names, every MIB whose file is not named after its module
        looked like something pysmi had gone and fetched by itself — 97 of them."""
        assert '_mibRawModules' in _fn(_read(UI), '_mibIsDependency')

    def test_the_compile_button_counts_the_work_and_not_the_rows(self):
        """A row is a module; the job walks file names. In a vendor archive the two differ,
        and the button promising 14 while the bar goes to 15 is the same disease as the 933%
        progress bar."""
        assert '_mibData.pending' in _fn(_read(UI), '_mibUpdateCompileBtn')

    def test_the_listing_ships_that_list_from_the_function_that_decides_it(self):
        admin = _read(MIB_ADMIN)
        assert "'pending':         _mib_resolver.pending_raw_mibs" in admin

    def test_pending_answers_the_name_the_compiler_needs(self):
        """Asked about the MODULE, answered with the FILE: handed a module name pysmi would
        look for a file of that name, find none, and go to the internet for it."""
        res = _read(RESOLVER)
        i = res.index('def pending_raw_mibs')
        body = res[i:res.index('\ndef ', i)]
        assert 'raw_module_name(path)' in body and 'compiled_mtime.get(mib)' in body
        assert 'out.append(stem)' in body


class TestACompileThatDidNothingSaysSo:
    """Reported: seven MIBs pending, compile, no error, still pending. Both halves were the
    file-name/module-name split, on the two sides of the same conversation with pysmi."""

    def test_an_import_is_resolved_by_the_name_it_asks_for(self):
        """pysmi tries the module name as a FILE name, which in a vendor archive finds
        nothing: DIFFSERV-DSCP-TC lives in `diffserv-dscp-tc-rfc3289.mib`."""
        res = _read(RESOLVER)
        assert 'def module_index' in res and 'def _module_reader' in res
        i = res.index('for _dir in raw_mib_dirs(raw_dir):')
        assert '_module_reader' in res[:i], 'the index has to be asked FIRST'

    def test_the_verdict_is_looked_up_under_both_names(self):
        """A module pysmi compiled comes back under the MODULE's name; one it could not parse
        under the name it was HANDED, because it never read the module out of the file."""
        body = _pyfn(_read(RESOLVER),
                     '_classify_compile_results')
        assert 'all_results.get(_mod(m))' in body and 'all_results.get(m)' in body

    def test_a_failure_is_reported_under_the_module_name(self):
        """Which is what the panel keys its rows and its stored reasons by."""
        body = _pyfn(_read(RESOLVER),
                     '_classify_compile_results')
        assert '_status[_mod(m)] = st' in body

    def test_the_store_is_cleared_by_what_the_job_reached(self):
        """`attempted` listed file names against a result keyed by module: always empty, so
        nothing was ever cleared and a MIB that had since compiled kept its old red row."""
        admin = _read(MIB_ADMIN)
        assert "result.get('attempted')" in admin
        assert 'raw_facts(_full)' in admin, 'the error index is keyed by module too'


class TestSomeMibsAreNeverCompiled:
    """RFC-1212 and RFC-1215 are macro definitions and nothing else: no `.py` is produced for
    them and none is missing. Shown as "pending" — which is what a row with a source and no
    compiled module says — they are a number that never goes down."""

    def test_they_have_a_state_of_their_own(self):
        body = _fn(_read(UI), '_mibRows')
        assert "'builtin'" in body and 'macro_only' in body

    def test_the_badge_says_why_there_is_no_module(self):
        assert 'mib_builtin_tooltip' in _fn(_read(UI), '_mibStateBadge')

    def test_the_row_offers_no_compile_button(self):
        """A button whose only outcome is nothing happening."""
        assert "r.state !== 'builtin'" in _fn(_read(UI), '_mibRow')

    def test_the_states_still_add_up(self):
        """Every row is counted once: a state missing from the counter reads as NaN in the
        chip and as a total that does not match the list."""
        assert 'builtin: 0' in _fn(_read(UI), '_mibCounts')

    def test_the_listing_ships_the_names_from_the_resolver(self):
        """One list of the two names. Two would be one of them updated on its own."""
        admin = _read(MIB_ADMIN)
        assert '_mib_resolver.MACRO_ONLY_MIBS' in admin
        assert "'RFC-1212'" not in admin, 'the admin surface knows the names on its own'


class TestACompiledModuleCanOutliveItsSource:
    """Delete the copy a duplicated module was compiled from and the `.py` stays — it is what
    pysnmp loads, and dropping it would take the module out of service over a tidy-up. But
    nothing is newer than anything now, so the clock cannot notice, and the row would read
    "compiled" while what is compiled came from a file nobody can open any more."""

    def test_the_row_compares_against_where_the_py_came_from(self):
        body = _fn(_read(UI), '_mibRows')
        assert 'r.pySource' in body and "r.state = 'stale'" in body

    def test_the_badge_says_which_kind_of_outdated_it_is(self):
        """"The source is newer" is advice about a file you can open. This one is about one
        that is not there, and doing the same thing about it has a different reason."""
        assert 'mib_stale_gone_tooltip' in _fn(_read(UI), '_mibStateBadge')

    def test_the_server_agrees_that_it_is_pending(self):
        """The chips and the compile button read two different answers — that is how the
        panel once showed "Pending 0, Errors 1" over a button compiling three."""
        res = _read(RESOLVER)
        i = res.index('def pending_raw_mibs')
        body = res[i:res.index('\ndef ', i)]
        assert 'compiled_source' in body and 'orphaned' in body

    def test_provenance_is_read_where_it_is_written(self):
        """pysmi writes the header; the resolver owns everything about compiled modules. The
        admin surface asks it rather than parsing a .py of its own."""
        admin = _read(MIB_ADMIN)
        assert 'ASN.1 source' not in admin
        assert '_mib_resolver.compiled_source' in admin


class TestWhatDeletingLeavesBehind:
    """`compiled/` is flat and its files are named after the MODULE: nothing in a .py says
    which folder its source lived in. So deleting a vendor folder cannot take its
    compilations with it — they stay, loadable, uncompilable, and counted as "dependencies"
    among the handful of real ones."""

    def test_the_leftovers_are_a_state_of_their_own(self):
        """Not a footnote on "dep": the two need opposite things done to them, and a chip
        that partitions the list is what makes "is there anything to clean?" answerable
        without clicking anything."""
        ui = _read(UI)
        assert 'mib_filter_stray' in _fn(ui, '_mibStateDefs')
        assert "stray: 0" in _fn(ui, '_mibCounts')
        assert 'mib_stray' in _fn(ui, '_mibStateBadge')

    def test_they_are_grouped_apart_from_the_folders(self):
        """A folder that no longer exists is not a folder to list. They get a group of their
        own, like dependencies, so the folder selector keeps naming real folders."""
        ui = _read(UI)
        assert '_MIB_STRAY_GROUP' in ui
        assert '_MIB_STRAY_GROUP' in _fn(ui, '_mibGroupLabel')
        assert '_MIB_STRAY_GROUP' in _fn(ui, '_mibGroups')

    def test_the_cleanup_reports_before_it_deletes(self):
        """Two actions, and the read-only one comes first: a number nobody can check before
        agreeing to it is not a confirmation."""
        ui = _read(UI)
        body = _fn(ui, '_mibCleanLibrary')
        assert 'library_leftovers' in body and 'clean_library' not in body
        assert 'showConfirmModal' in body
        assert 'clean_library' in _fn(ui, '_mibCleanConfirmed')

    def test_the_broom_is_where_the_compiling_happens(self):
        """What it sweeps is compiled OUTPUT — a module whose source was deleted, and the
        folder that source lived in. In the library's head it was an action on the library
        about something the library does not do."""
        assert 'id="mibCleanBtn"' in _compile_markup()
        assert 'mibCleanBtn' not in _manager_markup()
        assert 'mib_clean_btn' in _fn(_read(UI), '_snmpCompilePageLabels')

    def test_it_only_shows_up_when_there_is_something_to_sweep(self):
        """A broom on a tidy library is a button whose whole answer is "nothing"."""
        body = _fn(_read(UI), '_mibUpdateCleanBtn')
        assert "btn.style.display = n ? '' : 'none'" in body
        assert '_mibUpdateCleanBtn(' in _fn(_read(UI), '_mibCompileRender')

    def test_the_library_says_it_without_offering_to_do_it(self):
        """The notice is the "no source" line in the rail, with its count and the rows
        behind it — which is a thing to look at, not a second place to act."""
        ui = _read(UI)
        assert 'mib_filter_stray' in _fn(ui, '_mibStateDefs')
        assert '_mibUpdateCleanBtn' not in _fn(ui, '_mibFilterLists')

    def test_a_dependency_is_never_swept_up_with_them(self):
        """A compiled module pysmi did not read out of `raw/` cannot be rebuilt from
        anything here, and the modules that import it stop loading the day it goes."""
        admin = _read(MIB_ADMIN)
        i = admin.index('def _stray_compiled')
        body = admin[i:admin.index('\n    @', i)]
        assert 'if not src:' in body and 'continue' in body
        assert 'if mib in declared:' in body

    def test_the_names_it_compares_come_from_inside_the_files(self):
        """`trunk.mib` declares IEEE8023-LAG-MIB and the .py is named after the module. A
        comparison by file name deletes what is still there and keeps what is not."""
        admin = _read(MIB_ADMIN)
        i = admin.index('def _declared_modules')
        body = admin[i:admin.index('\n    @', i)]
        assert 'raw_facts' in body and "['module']" in body

    def test_an_emptied_folder_is_swept_too(self):
        """`os.remove` removes files; the folder stays. A parent whose only content is empty
        folders is empty as well, which a walk that stops at the first branch never sees."""
        admin = _read(MIB_ADMIN)
        i = admin.index('def _empty_raw_dirs')
        body = admin[i:admin.index('\n    @', i)]
        assert 'os.walk' in body and 'dirname' in body
        clean = admin[admin.index('def clean_library'):]
        clean = clean[:clean.index('\n    @')]
        assert 'os.rmdir' in clean and 'reverse=True' in clean

    def test_the_symbol_catalogue_is_dropped_when_something_went(self):
        """It names modules that are no longer there. Discarded and not rebuilt: the next
        MIB Browser open pays for one rebuild, this click does not."""
        admin = _read(MIB_ADMIN)
        clean = admin[admin.index('def clean_library'):]
        clean = clean[:clean.index('\n    @')]
        assert '_mib_catalog.discard' in clean

    def test_the_report_is_read_only_and_the_sweep_is_not(self):
        """One of them deletes files. The audit log is the difference."""
        init = _read(SNMP_INIT)
        i = init.index('WATCHFUL_ACTIONS')
        actions = init[i:init.index('READ_ONLY_ACTIONS')]
        assert "'clean_library'" in actions and "'library_leftovers'" in actions
        ro = init[init.index('READ_ONLY_ACTIONS'):]
        ro = ro[:ro.index('})')]
        assert "'library_leftovers'" in ro and "'clean_library'" not in ro


class TestCompilingIsAPlaceAndNotAButton:
    """It was a button, a fold and a progress bar stacked over the list: two rows of the
    library spent on it whether anything was compiling or not, and the two things anybody
    needs when a compile goes wrong were the two hardest to reach — which sources resolve an
    IMPORTS was folded into a `<details>`, and what failed was a chip away from four thousand
    rows.

    It reads the same payload the library does and draws none of it: how much there is to do,
    and what failed with the reason beside it."""

    def test_the_view_holds_what_the_list_used_to_carry(self):
        markup = _compile_markup()
        for el in ('mibDepSrcList', 'mibCompileErrors', 'mibProgressSection', 'mibStopBtn'):
            assert 'id="%s"' % el in markup, f'{el} is not in the compile view'

    def test_none_of_it_is_left_over_the_library(self):
        """The point of moving it: the library's height goes to the library."""
        markup = _manager_markup()
        for el in ('mibDepSrcList', 'mibCompileErrors', 'mibCompileBtn'):
            assert 'id="%s"' % el not in markup, f'{el} is still stacked over the list'

    def test_the_fold_became_a_heading(self):
        """A `<details>` costs a row whether it is open or not, and what is inside it decides
        whether a compile can resolve an IMPORTS at all."""
        assert '<details' not in _compile_markup()
        assert "getElementById('mibDepSrcTitle')" in _fn(_read(UI), '_mibDepSrcRefreshSummary')

    def test_a_failure_carries_the_reason_and_the_line(self):
        """pysmi says "Bad grammar near offset 558 … line 21". The number is the difference
        between "this file is broken" and being able to look at what is broken."""
        body = _fn(_read(UI), '_mibErrorRow')
        assert '_mibErrorLine' in body and '_mibShowRawDetails' in body
        assert '_compileMibs(' in body, 'a fixed file cannot be tried again from here'

    def test_pending_comes_from_the_server_and_not_from_the_rows(self):
        """A row is a module and the job walks file NAMES: the two differ whenever a module
        arrives twice under different names, which in a vendor archive is most of them. The
        panel once promised 14 and the bar went to 15."""
        body = _fn(_read(UI), '_mibCompileRender')
        assert '_mibData.pending' in body

    def test_the_view_paints_no_list(self):
        """It reads the whole inventory and shows none of it — the library is where rows
        live, and two screens drawing the same four thousand rows is one too many."""
        body = _fn(_read(UI), '_mibCompileRender')
        assert '_mibRow(' not in body
        assert 'id="mibList"' not in _compile_markup()

    def test_a_job_started_anywhere_is_watchable_everywhere(self):
        """A compile runs server-side under a job id; the three views carry the same progress
        ids on purpose, because a `<template>` is inert and only the clone is ever live."""
        for markup in (_manager_markup(), _import_markup(), _compile_markup()):
            assert 'id="mibProgressBar"' in markup


class TestEachWayInSaysWhatItIs:
    """Three rows of controls stacked in a column read as one form with too many boxes: a
    URL field, a repo picker with a switch beside it, and a vendor archive with two buttons
    that mean different things. Nothing on the page said which was which, or that they were
    three separate ways in at all."""

    def test_every_source_is_a_card_with_a_name_on_it(self):
        markup = _import_markup()
        assert markup.count('class="card h-100"') + markup.count('class="card"') >= 4
        for title in ('mibUploadTitle', 'mibImportUrlTitle', 'mibGithubTitle', 'mibArchiveTitle'):
            assert 'id="%s"' % title in markup, f'{title} has no heading'

    def test_the_names_come_from_the_module_and_not_the_core(self):
        body = _fn(_read(UI), '_snmpImportPageLabels')
        for key in ('mib_upload_title', 'mib_import_url_title', 'mib_github_title',
                    'mib_archive_title'):
            assert key in body
        import json
        for lang in ('es_ES', 'en_EN'):
            with open(os.path.join(SRC, 'watchfuls', 'snmp', 'lang', lang + '.json'),
                      encoding='utf-8') as fh:
                ui = json.load(fh).get('ui') or {}
            for key in ('mib_upload_title', 'mib_import_url_title', 'mib_github_title',
                        'mib_archive_title', 'view_compile'):
                assert ui.get(key), f'{key} has no word in {lang}'

    def test_the_report_still_gets_the_rest_of_the_page(self):
        """The cards are the top of the page and refuse to grow; what "Compare" answers is
        four thousand rows and takes everything that is left."""
        markup = _import_markup()
        i = markup.index('id="mibArchiveResult"')
        assert 'flex-shrink-0' in markup[:i]
        assert 'class="ss-vfill"' in markup[i:i + 120]


class TestNarrowingAListYouAreAlreadyLookingAt:
    """The rail answers WHICH rows; the bar over the list answers how many of them you are
    looking at, in what order, and what you do with the ones you ticked.

    Two of the rail's lines are not states — a duplicated module is still compiled or
    pending, and so is one somebody edited here — and they were tried as toggles over the
    list, which would have let the two kinds combine. They read as two behaviours in one
    screen: eight lines you pick one of, and two switches somewhere else. They are lines of
    the same list now, behaving the same way, LAST so the partition above them stays one."""

    def test_what_cuts_across_the_states_comes_after_them(self):
        body = _fn(_read(UI), '_mibStateDefs')
        i = body.index("'stray'") if "'stray'" in body else body.index("'builtin'")
        for key in ("'dupe'", "'edited'"):
            assert body.index(key) > i, f'{key} is inside the partition'

    def test_edited_is_a_line_and_not_a_badge_you_have_to_hunt_for(self):
        """The first thing worth knowing about a MIB that started misbehaving after somebody
        fixed it, and it could only be read one row at a time as a `v3` badge."""
        ui = _read(UI)
        assert "'edited'" in _fn(ui, '_mibStateDefs')
        assert 'edited: 0' in _fn(ui, '_mibCounts')
        assert "_mibFilter === 'edited'" in _fn(ui, '_mibTreeRows')


    def test_a_search_looks_at_the_file_names_too(self):
        """A row is titled by the MODULE, and that is not what anybody types. Searching for
        `rfc` in a library holding eight files called `rfc*.mib` found nothing, because every
        one of them declares a module named after what it describes — `rfc2011.mib` is IP-MIB
        and `rfc2737.mib` is ENTITY-MIB."""
        body = _fn(_read(UI), '_mibMatches')
        assert 'r.raws' in body, 'the file names are not searched'
        assert 'r.key' in body

    def test_a_second_word_narrows(self):
        """Typing another one is how somebody says "not those": as one long substring the
        second word could only ever match less by accident of order."""
        ui = _read(UI)
        assert 'terms.every' in _fn(ui, '_mibMatches')
        assert 'split(' in _fn(ui, '_mibTreeRows')

    def test_the_box_is_over_the_list_it_narrows(self):
        """It was at the top of the rail, which is where the states and the folders are —
        the two things you PICK. Free text narrows what is already on screen, so it sits
        with the count of what is on screen."""
        markup = _manager_markup()
        i = markup.index('id="mibSearch"')
        assert i > markup.index('id="mibManagerBody"') - 4000  # same block as the list bar
        assert 'id="mibListBar"' in markup
        assert markup.index('id="mibSearch"') < markup.index('id="mibListBar"')
        assert "id=\"mibSearch\"" not in _fn(_read(UI), '_snmpRailShell'), \
            'the rail builds a second search box'

    def test_the_order_is_about_the_list_and_not_about_the_data(self):
        """Sorting cannot decide what belongs in the list, so it happens after the filtering
        — and by name is the order the library HAS, which is why it is the one that changes
        nothing."""
        ui = _read(UI)
        vis = _fn(ui, '_mibVisibleRows')
        assert '_mibSortRows(' in vis and '_mibInFolder' in vis
        body = _fn(ui, '_mibSortRows')
        assert "'size'" in body and "'date'" in body
        assert 'rows.slice()' in body, 'sorting in place reorders the caller\'s array'
        assert body.rstrip().endswith('return rows;'), 'by name is not the untouched order'

    def test_the_bar_separates_what_you_see_from_what_you_ticked(self):
        """Two different subjects on one row: the left is the list, the right is the
        selection. Mixed, "None" reads as a filter."""
        body = _fn(_read(UI), '_mibListBarHtml')
        i = body.index('ms-auto')
        for before in ('_mibSetSort', 'mib_showing'):
            assert body.index(before) < i, f'{before} is on the selection side'
        for after in ('_mibSelectAll', '_mibDeselectAll', 'mibDeleteSelGroup'):
            assert body.index(after) > i, f'{after} is on the list side'

    def test_what_appears_with_a_selection_does_not_shove_what_is_always_there(self):
        """"All" and "None" are the buttons somebody is clicking AT THE TIME. Rendered before
        the two that come and go with the selection, every tick and untick slid them
        sideways under the cursor."""
        body = _fn(_read(UI), '_mibListBarHtml')
        for moves in ('mibCompileSelBtn', 'mibDeleteSelGroup'):
            assert body.index(moves) < body.index('_mibSelectAll'), \
                f'{moves} pushes "All" and "None" when it appears'


class TestSeveralFilesOneModule:
    """``×3`` was the fact, not the question. Which of the three is being compiled, and
    whether they even differ, are the two things somebody needs to decide which one stays —
    and while nobody decides, the alphabet decides."""

    def test_the_badge_opens_the_comparison(self):
        """A tooltip listing three paths is a tooltip you cannot act on."""
        body = _fn(_read(UI), '_mibRow')
        assert '_mibDupesShow' in body

    def test_it_says_whether_they_differ_without_opening_it(self):
        """Identical copies are clutter; different ones are a decision waiting. A badge that
        looks the same for both makes you open every one of them to find out which."""
        body = _fn(_read(UI), '_mibRow')
        assert 'bg-warning' in body and 'r.dupe' in body

    def test_the_eye_opens_the_copy_that_is_actually_used(self):
        """Opening the first by alphabet shows a file that may have nothing to do with what
        got compiled — which is the whole confusion this screen is about."""
        body = _fn(_read(UI), '_mibRow')
        assert 'r.dupe && r.dupe.used' in body

    def test_the_comparison_is_server_side(self):
        """The listing ships a hash per copy, never the content: comparing in the page would
        mean fetching every duplicate in full to throw most of it away."""
        admin = _read(MIB_ADMIN)
        dupes = admin[admin.index('def _duplicate_sources'):admin.index('def diff_mib_files')]
        assert "'sha'" in dupes and "'content'" not in dupes
        assert 'def diff_mib_files' in admin

    def test_one_derivation_of_what_the_difference_is(self):
        """Versions and files ask the same question. Two implementations of it stay in step
        until the day the context lines or the cap change in one of them."""
        admin = _strip_comments(_read(MIB_ADMIN))
        assert admin.count('difflib.unified_diff(') == 1

    def test_which_copy_wins_is_asked_of_pysmi(self):
        """It follows pysmi's own directory walk and extension order. Re-derived here, it
        would be right until the release that changed it and silent about having stopped."""
        res = _read(RESOLVER)
        i = res.index('def resolve_raw_sources')
        body = res[i:res.index('\ndef ', i)]
        assert 'FileReader' in body

    def test_the_tree_is_walked_once_for_the_whole_batch(self):
        """The reader re-walks the entire tree on every single lookup, and the listing asks
        it once per duplicate — on a library of a thousand files that is the refresh."""
        res = _read(RESOLVER)
        assert 'def resolve_raw_sources' in res, 'one name at a time is one walk at a time'

    def test_the_filter_is_not_a_state(self):
        """A duplicated module is still compiled, or pending, or failed — so it is asked for
        the way the states are, but it is not one of them: it comes after them, and the rows
        it answers with are rows the lines above already counted."""
        ui = _read(UI)
        body = _fn(ui, '_mibTreeRows')
        assert "_mibFilter === 'dupe'" in body and 'r.state === _mibFilter' in body
        assert 'c.dupe' in _fn(ui, '_mibCounts')

    def test_the_line_is_only_there_when_it_counts_something(self):
        """A line that always reads zero is a line nobody reads."""
        assert 'if (c.dupe)' in _fn(_read(UI), '_mibStateDefs')

    def test_deleting_a_copy_says_the_module_needs_compiling_again(self):
        """Delete the copy that was being compiled and another takes over — the compiled
        module now comes from a file that is not the one on disk any more."""
        body = _fn(_read(UI), '_mibDupDeleteConfirmed')
        assert 'mib_dupe_deleted_used' in body

    def test_it_is_a_declared_action(self):
        init = _read(SNMP_INIT)
        acts = init[init.index('WATCHFUL_ACTIONS'):init.index('WATCHFUL_TOOLBAR')]
        assert "'diff_mib_files'" in acts
        assert "'diff_mib_files'" in acts[acts.index('READ_ONLY_ACTIONS'):], \
            'reading a diff writes nothing'


class TestTwoProblemsAreNotOneProblem:
    """Files collide on a module name for two different reasons: they are copies of one MIB,
    or they are different MIBs whose first line was copy-pasted. The screen gave one answer to
    both — "pick the one that stays" — and for the second that answer deletes a whole MIB."""

    def test_the_screen_says_when_they_are_not_copies(self):
        body = _fn(_read(UI), '_mibDupesHtml')
        assert '_strangers' in body and 'mib_dupe_strangers' in body

    def test_it_does_not_open_a_diff_between_unrelated_files(self):
        """A diff of two MIBs that share nothing is a full rewrite: every line removed and
        every line added, which reads as a comparison gone wrong."""
        assert 'd.kinship !== 0' in _fn(_read(UI), '_mibDupesShow')

    def test_kinship_is_measured_where_the_files_are_read(self):
        """…which is the action that opens a group, and no longer the listing: reading 529
        files to answer about panels nobody had opened was four minutes of every load."""
        admin = _read(MIB_ADMIN)
        assert 'def _kinship' in admin
        assert "'kinship': _kinship(paths)" in admin
        # Sliced to the next method: `_pyfn` cuts at the next TOP-LEVEL def, and these are
        # classmethods — it would swallow half the class and pass on somebody else's code.
        _i = admin.index('def _duplicate_sources')
        _body = admin[_i:admin.index('\n    @classmethod', _i)]
        assert 'kinship' not in _body and 'sha' not in _body, \
            'the listing is reading the files again'

    def test_it_is_the_descriptors_that_are_compared(self):
        """Not the size, not the text: what a MIB declares is what survives being copied,
        renamed and re-indented."""
        lint = _read(LINT)
        assert 'def declared_names' in lint


class TestTheDateDecidesAndIsShown:
    """`LAST-UPDATED` is what tells two copies of a standard module apart — 2002 against 1999
    in the pair that prompted this — and it was only visible twenty lines into the diff."""

    def test_the_column_exists_only_when_something_fills_it(self):
        """A quarter of a real library declares no date at all (SNMPv2-TC has no
        MODULE-IDENTITY), and a column of dashes is a column that costs width and says
        nothing."""
        body = _fn(_read(UI), '_mibDupesHtml')
        assert '_hasDates' in body

    def test_newest_is_claimed_only_when_the_dates_differ(self):
        """Two copies of one date have no newest, and one date against a blank is not a
        comparison — the other file did not say."""
        body = _fn(_read(UI), '_mibDupesHtml')
        assert 'new Set(' in body and '.size > 1' in body

    def test_a_file_that_does_not_say_is_not_shown_as_older(self):
        body = _fn(_read(UI), '_mibDupRow')
        assert 'mib_dupe_no_updated' in body

    def test_it_is_read_beside_the_module_name(self):
        """Both facts live in the same header, and the listing wants both of every file: two
        reads and two caches for one header would be one of them going stale on its own."""
        res = _read(RESOLVER)
        i = res.index('def raw_facts')
        body = res[i:res.index('\ndef ', i)]
        assert 'module' in body and 'updated' in body
        assert body.count('fh.read(') == 1


class TestDeletingIsNotOneThing:
    """A row is a MODULE and stands for two files: the source somebody wrote and the .py
    pysmi made from it. Deleting them together is right almost always — and the two cases
    where it is not are the ones that matter. A compiled module is an OUTPUT: dropping it is
    how you ask for it to be built again from a source that has since changed underneath it.
    And a source can go while the .py stays loaded, which is a thing to do on purpose and
    never by accident."""

    def test_the_two_halves_can_be_asked_for_separately(self):
        body = _fn(_read(UI), '_mibArtifacts')
        assert "scope !== 'compiled'" in body and "scope !== 'raw'" in body

    def test_no_scope_still_means_both(self):
        """Every existing caller passes nothing — a scope that defaulted to one half would
        turn every delete on the screen into half a delete."""
        assert 'function _mibArtifacts(rows, scope)' in _read(UI)

    def test_the_menu_is_only_there_when_there_are_two_things(self):
        """With one file there is nothing to choose, and a caret says there is."""
        body = _fn(_read(UI), '_mibDeleteBtn')
        assert '!r.raws.length || !r.py' in body and 'return one' in body

    def test_the_row_and_the_selection_share_one_menu(self):
        """The same three choices over a different set. Two copies of a menu are two menus
        that drift."""
        ui = _read(UI)
        assert '_mibDeleteMenu' in _fn(ui, '_mibDeleteBtn')
        assert '_mibDeleteMenu' in _fn(ui, '_mibListBarHtml')

    def test_the_question_says_what_SURVIVES(self):
        """What goes is half of it; what stays is the half somebody gets wrong. Deleting the
        source leaves a compiled module still in use, which does not look like a deletion at
        all until the next compile."""
        body = _fn(_read(UI), '_mibDeleteMsg')
        assert 'mib_delete_compiled_confirm' in body and 'mib_delete_raw_confirm' in body

    def test_the_history_is_not_offered_when_only_the_py_goes(self):
        """The history is the history OF the source. A .py is not something anybody edited."""
        assert "scope !== 'compiled'" in _fn(_read(UI), '_mibDeleteRow')

    def test_hiding_the_selection_button_hides_its_caret(self):
        """The button is inside a group now: hiding it alone leaves the caret on its own."""
        assert "getElementById('mibDeleteSelGroup')" in _fn(_read(UI), '_mibUpdateDeleteBtn')

    def test_a_scope_the_selection_has_nothing_of_says_so(self):
        """Every row picked may still be uncompiled. Silence there reads as a click that did
        not register."""
        assert 'mib_delete_none_of_that' in _fn(_read(UI), '_mibDeleteSelected')


class TestTheHistoryIsServerSide:

    def test_the_module_declares_its_own_table(self):
        """The mechanism for a module keeping data in the shared database, used as intended:
        a file beside the MIBs would be per-container, and a deployment with a web container
        and a worker container shares the database and not the disk."""
        init = _read(SNMP_INIT)
        assert 'def discover_db_tables' in init
        assert 'mib_versions.SCHEMA' in init

    def test_editing_needs_edit_rights_and_reading_does_not(self):
        """`READ_ONLY_ACTIONS` is what the route checks to decide whether `modules_view` is
        enough. A write action listed there is a write anybody who can look can do."""
        init = _read(SNMP_INIT)
        acts = init[init.index('WATCHFUL_ACTIONS'):init.index('WATCHFUL_TOOLBAR')]
        ro = acts[acts.index('READ_ONLY_ACTIONS'):]
        for a in ('save_mib_source', 'restore_mib_version', 'list_mib_versions',
                  'get_mib_version'):
            assert f"'{a}'" in acts, f'{a} is not a declared action — the route 404s'
        for a in ('save_mib_source', 'restore_mib_version'):
            assert f"'{a}'" not in ro, f'{a} is marked read-only — anyone who can look can write'
        for a in ('list_mib_versions', 'get_mib_version'):
            assert f"'{a}'" in ro, f'{a} audits a row for every look'

    def test_the_actor_reaches_the_module(self):
        """A history that says only WHAT changed answers half the question on a panel with
        more than one administrator."""
        routes = _read(os.path.join(SRC, 'lib', 'core', 'modules', 'routes.py'))
        assert "config['__user__'] = session.get('username', '')" in routes


class TestManyMibsStayWorkable:
    """Twenty MIBs are a list. A repository import brings two thousand, and a flat list of
    two thousand is unreadable however fast it draws — the folders the import already keeps
    are the structure that was there all along, so the list uses them."""

    def test_the_group_is_decided_after_the_state_and_not_before(self):
        """It depends on the state — a dependency has no folder — and reading a property the
        line above has not assigned yet is `undefined`, which compares false and quietly puts
        every dependency in the top-level group. Ninety-four of them, filed as if somebody had
        chosen them."""
        body = _fn(_read(UI), '_mibRows')
        assert body.index('r.state = ') < body.index('r.group ='), \
            'the group is computed before the state it depends on'

    def test_dependencies_are_not_filed_as_if_somebody_chose_them(self):
        ui = _read(UI)
        assert '_MIB_DEP_GROUP' in _fn(ui, '_mibRows')
        assert 'mib_group_deps' in _fn(ui, '_mibGroupLabel')

    def test_they_sort_last_because_it_says_so(self):
        """The key is a control character, and leaving the order to how a collation feels
        about one is having an opinion about something nobody should have to."""
        assert 'rank' in _fn(_read(UI), '_mibGroups')

    def test_a_small_tree_is_still_a_plain_list(self):
        """Grouping twenty files is pure overhead: the headers exist for the case that does
        not fit, and must not tax the case that does."""
        ui = _read(UI)
        assert '_MIB_AUTO_EXPAND' in _fn(ui, '_mibListHtml')
        assert 'shown.map(r => _mibRow(r))' in _fn(ui, '_mibListHtml')

    def test_the_folders_are_a_tree_and_not_a_flat_list(self):
        """`librenms/nokia/aos6` is three folders, and four hundred of them flattened into a
        `<select>` in alphabetical order is a control you can only use if you already know
        the answer. Split on the separator, nested, and each node counting its whole
        subtree."""
        body = _fn(_read(UI), '_mibFolderTree')
        assert "split('/')" in body and 'kids' in body

    def test_choosing_a_folder_shows_what_is_under_it(self):
        """A node that counted its subtree and then showed only its own direct children
        would be a number beside a folder that looks empty."""
        body = _fn(_read(UI), '_mibInFolder')
        assert "startsWith(_mibFolder + '/')" in body
        assert '_mibInFolder' in _fn(_read(UI), '_mibVisibleRows')

    def test_the_root_folder_is_not_the_same_thing_as_every_folder(self):
        """Both were the empty string: the rows directly under `raw/` carry `group === ''`,
        and so does "no folder chosen". Picking the root therefore selected all of them and
        lit up both lines at once. It gets a key of its own, like the other two
        pseudo-folders, and the filter knows what it means."""
        ui = _read(UI)
        assert '_MIB_ROOT_GROUP' in ui
        assert '_MIB_ROOT_GROUP' in _fn(ui, '_mibFolderTree')
        body = _fn(ui, '_mibInFolder')
        assert '_mibFolder === _MIB_ROOT_GROUP' in body and 'return !r.group' in body

    def test_opening_a_folder_and_picking_it_are_two_answers(self):
        """The twist is its own control, so it stops the click reaching the row — and a row
        picked inside a closed parent opens every level above it, or the selection is
        somewhere nobody can see."""
        ui = _read(UI)
        item = _fn(ui, '_mibRailItem')
        assert 'event.stopPropagation()' in item and '_mibToggleFolder' in item
        assert '<button' not in item, 'a control inside a control: the browser picks a winner'
        assert 'role="button"' in item, 'the rail is not reachable by keyboard'
        assert '_mibOpenFolders.add' in _fn(ui, '_mibSetFolder')

    def test_a_search_opens_the_folders_it_matched_in(self):
        """Typing something that exists and being shown nothing, because the match is inside
        a closed folder, is a search that reads as broken."""
        assert '!!q ||' in _fn(_read(UI), '_mibListHtml')

    def test_a_folder_can_be_selected_from_its_header(self):
        """Compiling or deleting a vendor's worth of MIBs is one of the few things anybody
        does in bulk here, and doing it by ticking six hundred boxes is not doing it."""
        ui = _read(UI)
        assert '_mibGroupSelect' in _fn(ui, '_mibGroupHeader')

    def test_the_header_checkbox_is_not_inside_the_collapse_button(self):
        """A control inside a control: the browser is entitled to swallow the click, and
        which of the two wins is not a thing to leave to chance."""
        body = _fn(_read(UI), '_mibGroupHeader')
        assert '<button' not in body, 'the header is a button again, with a checkbox in it'
        assert 'role="button"' in body, 'the collapse target is not reachable by keyboard'

    def test_it_selects_what_is_visible_and_not_what_the_folder_holds(self):
        """With a state chip or a search active, a tick beside four rows must not select the
        six hundred behind them."""
        assert '_mibVisibleRows()' in _fn(_read(UI), '_mibGroupSelect')

    def test_a_half_selected_folder_does_not_look_untouched(self):
        """`indeterminate` is a property, not an attribute, so it cannot be written into the
        markup — and an empty box on a folder with half its rows ticked is a lie."""
        ui = _read(UI)
        assert 'indeterminate' in _fn(ui, '_mibGroupCheckStates')
        assert '_mibGroupCheckStates()' in _fn(ui, '_mibFilterLists')

    def test_the_folder_says_how_much_is_left_and_not_how_much_there_is(self):
        """A folder of six hundred says nothing on its own; "588/612" says where the work is
        and which vendor to open. A stale module does not count as done — it was compiled from
        bytes that are no longer there, which is the whole reason that state exists."""
        body = _fn(_read(UI), '_mibGroupHeader')
        assert "r.py && r.state !== 'stale'" in body
        assert '${done}/${rs.length}' in body

    def test_the_tree_counts_what_the_filter_left_and_not_what_the_folder_holds(self):
        """"Where is the work" is what a tree beside a state filter is asked, and a count of
        everything answers a different question. It must NOT follow the folder, though: the
        branch you are standing on would be the only one with a number on it."""
        ui = _read(UI)
        assert '_mibTreeRows()' in _fn(ui, '_mibRailHtml')
        assert '_mibInFolder' not in _fn(ui, '_mibTreeRows')
        assert '_mibRailHtml(all)' in _fn(ui, '_mibFilterLists')


class TestTheCompileButtonSaysWhatItDoes:
    """It said "compile all" and did neither: it walked every MIB and let pysmi skip the
    up-to-date ones. Two actions now, because they are two things."""

    def test_the_default_action_is_the_pending_one(self):
        """It is what somebody presses without reading it, so it had better be the one that
        does the work and not the inventory — and it is the primary button of the view."""
        markup = _compile_markup()
        assert "_compileMibs(null, 'pending')" in markup
        assert 'btn-primary' in markup[:markup.index("_compileMibs(null, 'pending')")]

    def test_rebuilding_everything_is_the_second_button_and_asks(self):
        """Slow, almost never wanted, and indistinguishable from the fast one once it is
        running. It was a dropdown item over the list; with a view of its own there is room
        to write it out, and what it costs is still a question before it starts."""
        markup = _compile_markup()
        assert '_mibRebuildAll()' in markup
        i, j = markup.index("_compileMibs(null, 'pending')"), markup.index('_mibRebuildAll()')
        assert i < j, 'the slow one comes first'
        assert 'showConfirmModal' in _fn(_read(UI), '_mibRebuildAll')

    def test_the_two_labels_stay_on_their_own_buttons(self):
        """The compile job restores the main button's label when it ends, and it restored the
        DROPDOWN item's — so "compile pending" renamed itself to "rebuild everything" the first
        time anybody compiled, and stayed renamed. Two actions, one name, and the name that
        survived was the slow one."""
        # Comments here name the key on purpose; only the code counts.
        ui = _strip_comments(_read(UI))
        assert 'mib_compile_all' not in _fn(ui, '_compileMibs'), \
            "the running job puts the other action's label on this button"
        assert 'mib_compile_pending' in _fn(ui, '_compileMibs')

    def test_the_scope_reaches_the_job(self):
        assert "scope: scope || 'pending'" in _fn(_read(UI), '_compileMibs')

    def test_finding_nothing_to_do_is_said_out_loud(self):
        """A job that ends instantly and silently is a button that reads as broken — the
        exact reading this screen has had to unlearn once already."""
        assert 'up_to_date' in _fn(_read(UI), '_mibHandleCompileResult')

    def test_a_module_compiled_from_bytes_that_are_gone_is_its_own_state(self):
        """Editing a MIB produces this every single time: the row said "compiled" and meant
        "compiled from something else", which sends somebody looking for a bug in the sampler
        instead of pressing compile. As a FLAG on 'compiled' it also sat inside that count, so
        the chips read "Pending 0, Compiled 97" while the button set off to do three files."""
        ui = _read(UI)
        assert "'stale'" in _fn(ui, '_mibRows')
        assert 'mib_stale' in _fn(ui, '_mibStateBadge')

    def test_the_chips_partition_the_list(self):
        """Every row in exactly one state. Anything else and the counts stop adding up to the
        total, which is the moment a number on screen becomes decoration."""
        body = _fn(_read(UI), '_mibCounts')
        for st in ('pending', 'stale', 'compiled', 'failed', 'dep'):
            assert f'{st}: 0' in body or f'all: rows.length' in body
        assert 'c[r.state]++' in body, 'a row can be counted in two places'

    def test_the_button_and_the_chips_answer_the_same_question(self):
        """"Compile pending" walks pending + outdated + failed. If the chips do not add up to
        what it is about to do, one of the two is lying — and the one people trust is the one
        they can see."""
        body = _fn(_read(UI), '_mibToCompile')
        for st in ('pending', 'stale', 'failed'):
            assert f"'{st}'" in body

    def test_the_button_says_how_many_before_it_is_pressed(self):
        """Pressing it and being told a number you had no way of predicting is how this came
        to look like it was doing something else entirely."""
        ui = _read(UI)
        assert '_mibToCompile().length' in _fn(ui, '_mibUpdateCompileBtn')
        assert '_mibUpdateCompileBtn()' in _fn(ui, '_mibFilterLists')


class TestImportingIsItsOwnView:
    """Getting MIBs in has been three things: a folded `<details>` over the list, then a
    dialog, now a view of the section. What settled it is what "Compare" answers — one row
    per file in the vendor's archive, which against LibreNMS is four thousand of them. A
    panel showed nine, a dialog showed thirty; the answer is a page.

    A view and not a second section: same pane, same permission, a sub-path of its own
    (`/module/snmp/import`) that a person can send to somebody else."""

    def test_the_section_declares_its_views(self):
        """The module says which it has and names them in its own lang file — the core ships
        no string that names a module's view."""
        import json
        with open(os.path.join(SRC, 'watchfuls', 'snmp', 'schema.json'), encoding='utf-8') as fh:
            views = (json.load(fh)['__page__'].get('views') or [])
        assert [v['slug'] for v in views] == ['library', 'import', 'compile',
                                              'browser', 'profiles']
        for lang in ('es_ES', 'en_EN'):
            with open(os.path.join(SRC, 'watchfuls', 'snmp', 'lang', lang + '.json'),
                      encoding='utf-8') as fh:
                ui = json.load(fh).get('ui') or {}
            for v in views:
                assert ui.get(v['label']), f'{v["label"]} has no word in {lang}'

    def test_the_import_controls_live_in_the_import_view(self):
        """Each of them exactly once in the file: two live copies of an id is a control that
        fills one box and reads the other."""
        view = _import_markup()
        src = _read(MODALS)
        for el in ('mibImportUrlInput', 'mibGithubUrlInput', 'mibGithubRecursive',
                   'mibArchiveSel', 'mibArchiveResult'):
            assert 'id="%s"' % el in view, f'{el} is not in the import view'
            assert src.count('id="%s"' % el) == 1, f'{el} exists twice'
        assert 'mibImportPanel' not in src, 'the folded panel is still shipped'
        assert 'mibImportModal' not in src, 'the dialog is still shipped'
        assert 'mibImportUrlInput' not in _manager_markup()

    def test_the_renderer_paints_the_view_the_url_names(self):
        """A view is a sub-path, so which one to draw is a question about the URL — asked of
        the core, which owns paths, and not remembered here. Cloned once per view: coming
        back to the list must not cost the folder that was open and the search box."""
        fn = _fn(_read(UI), 'renderSnmpMibsPage')
        assert '_sbPageView(' in fn, 'the renderer decides the view by itself'
        assert IMPORT_TPL_ID in fn and TPL_ID in fn
        assert 'box.dataset.snmpView' in fn, 'nothing remembers which view is painted'

    def test_the_menu_is_the_way_in_and_the_bar_does_not_repeat_it(self):
        """The section's views are in the sidebar's flyout, all three of them. A toolbar
        button beside them is a second door onto the same room — and it was the first thing
        to wrap when the window narrowed. What is left in the library's bar is what is about
        the LIBRARY: whether pysmi is there, where the files are, re-read, tidy up."""
        ui = _read(UI)
        assert '_navPageView(' in _fn(ui, '_snmpGoToView')
        assert '_snmpGoToView(' in _fn(ui, 'openMibImportPage')
        # Neither way round: no button into a view, and no button back out of one either —
        # the flyout holds all three and is the same one click from anywhere.
        for markup in (_manager_markup(), _import_markup(), _compile_markup()):
            for gone in ('openMibImportPage()', 'openMibCompilePage()',
                         'openMibLibraryPage()'):
                assert gone not in markup, f'a view repeats the menu: {gone}'
        assert 'mibFileInput' not in _manager_markup(), 'the library still uploads'

    def test_every_view_wears_the_panel_s_head(self):
        """Configuration and Backups open with a bar: what you are looking at on the left,
        what you can do to it on the right. Three screens of one section that each invent
        their own top edge are three screens that look like three sections."""
        for markup, title in ((_manager_markup(), 'mibLibTitle'),
                              (_import_markup(), 'mibImportTitle'),
                              (_compile_markup(), 'mibCompileTitle')):
            assert 'ss-toolbar ss-toolbar-plain ss-toolbar-flush' in markup
            assert 'id="%s"' % title in markup, f'{title} has no head to sit in'
            # …and what is on the right is a GROUP with its own `ms-auto`. The toolbar pushes
            # its second child right, and the second child was the pysmi badge — hidden
            # whenever pysmi is installed, so the margin that does the pushing sat on an
            # element with no width and the whole right-hand end stayed by the title.
            if 'mibRefreshBtn' in markup:
                i = markup.index('ms-auto')
                assert i < markup.index('mibRefreshBtn'), 'the right-hand end is not pushed'
        css = _read(CSS)
        css = _read(CSS)
        m = re.search(r'\.ss-toolbar\.ss-toolbar-flush\s*\{([^}]*)\}', css)
        assert m, 'the flush toolbar variant is gone'
        assert 'border-radius: 0' in m.group(1)

    def test_uploading_a_file_is_one_of_the_ways_a_mib_gets_in(self):
        """It sat in the library's toolbar, which is where you look at MIBs and not where
        you add them — three ways in on one page and a fourth on another."""
        assert 'id="mibFileInput"' in _import_markup()
        assert 'mibUploadTitle' in _fn(_read(UI), '_snmpImportPageLabels')

    def test_the_comparison_report_fills_the_page(self):
        """The whole reason this is a page. `.ss-vfill` down to one `.ss-vscroll`: the header
        and the count stay put and the list takes whatever height the viewport has."""
        fn = _fn(_strip_comments(_read(UI)), '_mibArchiveReport')
        assert 'ss-vfill' in fn and 'ss-vscroll' in fn
        assert 'ss-scroll-box' not in fn, 'the report is still capped at a dialog\'s height'
        assert 'id="mibArchiveResult" class="ss-vfill"' in _import_markup()

    def test_opening_it_does_not_read_the_library(self):
        """The two dropdowns are what this view needs, and the answer that carries them was
        the whole inventory. It asks for the sources now — and the library's payload is not
        stored from here: half of it is missing, and whoever reads `_mibData` next must find
        the whole thing or nothing."""
        fn = _fn(_read(UI), '_mibImportViewLoad')
        assert "'list_mib_sources'" in fn
        assert "'list_mibs'" not in fn
        assert '_mibData =' not in fn, 'the import view leaves a half-filled payload behind'

    def test_two_renders_of_the_section_are_one_read(self):
        """Opening a section fires the render more than once — the tab shows, and the view is
        resolved — and the expensive call was made twice, racing itself."""
        fn = _fn(_read(UI), '_mibLoad')
        assert '_mibLoadInFlight' in fn
        assert 'return _mibLoadInFlight' in fn

    def test_a_download_with_no_declared_size_still_counts(self):
        """codeload zips the repository on the fly and answers `Transfer-Encoding: chunked`,
        so there is no Content-Length and no percentage to compute — the server does not know
        the size either. A bar with no number on it reads as hung, so what arrives is
        counted: megabytes, going up."""
        fn = _fn(_read(UI), '_mibArchiveProgress')
        assert 'MiB' in fn
        assert 'of ?' in fn or "of ? null" in fn or 'of ?' in fn.replace('  ', ' '),             'the label does not fall back to a count when there is no total'

    def test_comparing_means_going_to_look(self):
        """The main button fetches the archive; reusing the copy from last time is the
        dropdown. Both are one call apart, so the order is a decision and nothing enforces it
        but this: "Compare" that answers from something downloaded an hour ago is answering a
        question about an hour ago. (The import that follows does reuse, so the pair still
        costs one download.)"""
        markup = _import_markup()
        i = markup.index('id="mibArchiveCompareBtn"')
        main = markup[markup.rindex('<button', 0, i):markup.index('</button>', i)]
        assert '_mibArchiveRun(true, true)' in main, 'Compare does not go and look'
        drop = markup[markup.index('dropdown-menu', i):]
        assert '_mibArchiveRun(true)' in drop[:drop.index('</ul>')]
        assert 'mibArchiveCachedLabel' in drop[:drop.index('</ul>')]

    def test_a_running_job_survives_the_change_of_view(self):
        """Both views ship the same progress ids — a `<template>` is inert, so only the one
        that was cloned is ever in the document. That is what lets a download started on the
        import view keep counting on the list, instead of a bar that looks stopped."""
        assert 'id="mibProgressSection"' in _import_markup()
        assert 'id="mibProgressSection"' in _manager_markup()
        assert 'id="mibStopBtn"' in _import_markup()
        fn = _fn(_read(UI), 'renderSnmpMibsPage')
        assert '_mibGithubInProgress' in fn, 'the repaint forgets a job in flight'
        assert '_mibProgressBegin()' in fn
