# pytest.ini
[pytest]
pythonpath = .
testpaths = tests watchfuls
; addopts = -ra -q
addopts = -ra -v --tb=short -n auto
markers = integration: tests that require real external resources (DBs, network, etc.)
